### ISSUE TITLE
Unable to access frontend for FreshRSS or yarr

### ISSUE THREAD

**Issue by ScottG489** [einschmidt/hassio-addons#42]
When I installed either of these add-ons I was expecting to see a "OPEN WEB UI" button on the add-on's page, but I don't see one there.

Perhaps I'm missing the point of these add-ons. Are they only meant to provide either a stand-alone front or backend?

I see that the FreshRSS add-on has an option to specify a "base_url" which would indicate to me that you need to start up some backend service separately.

**Comment by einschmidt** [comment]
The "OPEN WEB UI" button is an optional feature for add-ons.
Without checking, it could be that the button is not configured for both add-ons.

The "OPEN WEB UI" button is a convenient entry point for the UI of both add-ons.
Alternatively, you can use the configured port to access the UIs.

Since both add-ons are typically used behind a proxy server, using the port method is not that big of an issue.

By the way, both add-ons provide front and backend.

**Comment by ScottG489** [comment]
Thanks for your response and work on these add-ons!

So turned out I had a slight DNS configuration problem so when I tried accessing the ports it didn't work, but they're there. Both seem to work great :)

That said, I would still be interested in having these served up via ingress and the standard add-on web ui. If I submitted a PR for this is that something you'd consider merging?

**Comment by einschmidt** [comment]
Glad to hear you are able to access the UIs. 👍

PRs are more than welcome.

**Comment by ScottG489** [comment]
Also quick question, but is there a way to load extensions? From what I saw in the docs you have to extract files in a certain dir and it didn't look like any dirs are mounted on the container.

If so I may also submit a PR for that :)

**Comment by einschmidt** [comment]
You are right, there are no folders mounted on the container for extensions.

While possible, there was just no request yet. Until now.
